### ISSUE TITLE
Add login and tracking of users

### ISSUE THREAD

**Issue by 1jamesthompson1** [1jamesthompson1/TAIC-report-summary#205]
## State

The viewer is a basic webapp completely open to the public.

## Problem

It lacks trackingany concept of a user and any tracking of search queries.

## Solution

I can add in some basic session management as well as search query and results logging. These logs could be sent somewhere so that I can analyze them at a later point to get some quantitative feedback.

**Comment by 1jamesthompson1** [comment]
It would be good to use azure sign in so that it can work within their usual single sign on. 
Information here about how this can be done https://github.com/Azure-Samples/ms-identity-python-webapp

**Comment by 1jamesthompson1** [comment]
The process of adding in logins will introduce the concept of a session to the app.

This means that session and user things can be done likel

- Restoring previous searchers
- ...

**Comment by 1jamesthompson1** [comment]
I have setup with Azure to allow for signing in with Azure accounts.

I am awaiting on how I can integrate this with my tests:
https://github.com/rayluo/identity/issues/33

I will then also need to figure out how to allow it in my organisation

Then also know how to update it to when I deploying it on the cloud.

**Comment by 1jamesthompson1** [comment]
This branch of work has been merged with the cloud version of the app that worked on heroku.

However I will move the deployment over to Azue App services.

For some reason it is not currently deploying to azure without errors. I am manually deploying using a zip deployment.

Useful guides

[Deploying python app](https://learn.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cmac-linux%2Cazure-cli%2Czip-deploy%2Cdeploy-instructions-azcli%2Cterminal-bash%2Cdeploy-instructions-zip-azcli)
[CD deployment](https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel%2Cpython%2Cpythonn)

I need to do a few things before this issue is closed:
- [ ] Get deployment working on my personal azure account
- [ ] Add in tracking of users by using the linked postgres db
- [ ] Move over to the TAIC implementations (This can only be done after repsonse from Garth about the resource providers and api permissions
