### ISSUE TITLE
Code review quality of life improvemens

### ISSUE THREAD

**Issue by 1jamesthompson1** [1jamesthompson1/TAIC-report-summary#289]
## State

The viewer has not had much time spent on making sure that it is working well and  clean in theback end.

A code review was conducted by an external agency and they provided some feedabck on areas that need/should be addressed.

Below is a list of things that should be implemented

## Task list
- [x] Set up time tracking that deletes stale task statuses and task results.
- [x] Configure Flask to delete old sessions using `PERMANENT_SESSION_LIFETIME` and `SESSION_FILE_THRESHOLD` parameters. This will prevent the `session["task_results"]` from being kept longer than necessary.
- [x] #296
- [x] Fix inconsistent Python function naming.
- [x] Remove the unused `Auth` variable in the global template.
- [x] Update `main.js` to set the maximum year dynamically instead of hardcoding it to 2024.
- [x] Correct the type shortcut icon in `base.html` from `x-type` to `png`.
- [x] Clean up `main.js` and delete unnecessary code:
  - [x] Fix inconsistent indentation.
  - [x] Improve the structure of the code.
  - [x] Remove unused safety recommendation link and links-visuals.
~~- [ ] Rename `db_URI` to something more descriptive.~~ _Not doing as dont want to change environment if possible_
- [x] Remove hardcoded hostname in the relevance search link and the CSV results printout.

**Comment by 1jamesthompson1** [comment]
I will not change the db_URI as this is only a small quality of life. It will mean I have update the environment variables in too many places.
