### ISSUE TITLE
Quote and reference checker

### ISSUE THREAD

**Issue by 1jamesthompson1** [1jamesthompson1/TAIC-report-summary#55]
As in #54 and #56 there are going to be reference and quotes to the reports added into the output.

Due to LLMs tendency to make this up things and halucinate we need  to check that these references can be checked.

I propose that this will done by taking the reponse from the model and sending it back trying to get all of the qoutes an references. Then these can be checked through regex and such.

Alternatively I could have the model give a more structured respojnse than can be easily parsed then sent through a regex style checker to find if they exist.

## Tasks

- [x] Add a section extractor to the reportExtractor class
- [x] Add in a quote extractor, This will look through some chunk of text and find all of the quotes.
- [x] Add a quote  validator, ie somthing that checks if a partiuclar quote exists in a specified piece of text.

**Comment by 1jamesthompson1** [comment]
There are more things that need to be done.

Firstly there is a tendency for the models to misattribute what sections a particuluar quote comes from. This is mainly when there are funnil formatted section in the PDF.

Secondly reparing wrong quotes. There need to be a system for both the weightings and the theme genreation in reparing a quote that could be fixed. It is much better to do that then rerun the query as that is expensive. This means that the reference checkor will need to return more information then just try or false. Maybe it can return a list of reference objects with the correction is need be.
